import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Service that generates real PDF files from markdown/text content.
class PdfExportService {
  /// Export content as a properly formatted PDF file
  static Future<String?> exportAsFile({
    required String title,
    required String content,
    String format = 'pdf',
  }) async {
    try {
      final sanitizedTitle = title
          .replaceAll(RegExp(r'[^\w\s-]'), '')
          .replaceAll(RegExp(r'\s+'), '_')
          .toLowerCase();

      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final fileName = '${sanitizedTitle}_$timestamp.pdf';

      String? dirPath;

      if (!kIsWeb) {
        // Try Downloads folder first (works on desktop)
        try {
          if (Platform.isWindows || Platform.isLinux || Platform.isMacOS) {
            final home = Platform.environment['USERPROFILE'] ??
                Platform.environment['HOME'] ??
                '';
            final downloadsDir = Directory('$home${Platform.pathSeparator}Downloads');
            if (await downloadsDir.exists()) {
              dirPath = downloadsDir.path;
            }
          }
        } catch (_) {}

        // Fallback to app documents directory
        if (dirPath == null) {
          final docsDir = await getApplicationDocumentsDirectory();
          dirPath = docsDir.path;
        }

        final filePath = '$dirPath${Platform.pathSeparator}$fileName';

        // Generate PDF
        final pdfBytes = await _generatePdf(title, content);
        final file = File(filePath);
        await file.writeAsBytes(pdfBytes);

        return file.path;
      }

      return null;
    } catch (e) {
      debugPrint('Export error: $e');
      return null;
    }
  }

  /// Generate PDF bytes from markdown content
  static Future<List<int>> _generatePdf(String title, String markdown) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(),
    );

    // Parse markdown into styled widgets
    final contentWidgets = _parseMarkdownToPdfWidgets(markdown);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(title, context),
        footer: (context) => _buildFooter(context),
        build: (context) => contentWidgets,
      ),
    );

    return await pdf.save();
  }

  /// Build PDF header
  static pw.Widget _buildHeader(String title, pw.Context context) {
    if (context.pageNumber == 1) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            padding: const pw.EdgeInsets.only(bottom: 12),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(
                  color: PdfColor.fromInt(0xFF6C63FF),
                  width: 2,
                ),
              ),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  title.replaceAll('_', ' '),
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                    color: const PdfColor.fromInt(0xFF6C63FF),
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Generated by DeepTutor • ${DateTime.now().toString().split('.')[0]}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColor.fromInt(0xFF9E97B8),
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
        ],
      );
    }
    return pw.SizedBox.shrink();
  }

  /// Build PDF footer
  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: PdfColor.fromInt(0xFFDDDDDD), width: 0.5),
        ),
      ),
      padding: const pw.EdgeInsets.only(top: 8),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'DeepTutor — AI-Powered Learning Assistant',
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColor.fromInt(0xFF999999),
            ),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColor.fromInt(0xFF999999),
            ),
          ),
        ],
      ),
    );
  }

  /// Parse markdown text into PDF widgets
  static List<pw.Widget> _parseMarkdownToPdfWidgets(String markdown) {
    final widgets = <pw.Widget>[];
    final lines = markdown.split('\n');

    for (int i = 0; i < lines.length; i++) {
      final line = lines[i];
      final trimmed = line.trim();

      if (trimmed.isEmpty) {
        widgets.add(pw.SizedBox(height: 6));
        continue;
      }

      // Horizontal rule
      if (trimmed == '---' || trimmed == '***' || trimmed == '___') {
        widgets.add(
          pw.Container(
            margin: const pw.EdgeInsets.symmetric(vertical: 8),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(
                  color: PdfColor.fromInt(0xFFCCCCCC),
                  width: 0.5,
                ),
              ),
            ),
          ),
        );
        continue;
      }

      // Headers
      if (trimmed.startsWith('### ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(top: 10, bottom: 4),
          child: pw.Text(
            _stripInlineMarkdown(trimmed.substring(4)),
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: const PdfColor.fromInt(0xFF00A0CC),
            ),
          ),
        ));
        continue;
      }
      if (trimmed.startsWith('## ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(top: 12, bottom: 4),
          child: pw.Text(
            _stripInlineMarkdown(trimmed.substring(3)),
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
              color: const PdfColor.fromInt(0xFF7C3DB3),
            ),
          ),
        ));
        continue;
      }
      if (trimmed.startsWith('# ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(top: 14, bottom: 6),
          child: pw.Text(
            _stripInlineMarkdown(trimmed.substring(2)),
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
              color: const PdfColor.fromInt(0xFF4A40CC),
            ),
          ),
        ));
        continue;
      }

      // Bullet points
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(left: 16, bottom: 3),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 5,
                height: 5,
                margin: const pw.EdgeInsets.only(top: 5, right: 8),
                decoration: const pw.BoxDecoration(
                  color: PdfColor.fromInt(0xFF6C63FF),
                  shape: pw.BoxShape.circle,
                ),
              ),
              pw.Expanded(
                child: _buildRichText(trimmed.substring(2)),
              ),
            ],
          ),
        ));
        continue;
      }

      // Numbered list
      final numMatch = RegExp(r'^(\d+)\.\s+(.+)$').firstMatch(trimmed);
      if (numMatch != null) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(left: 16, bottom: 3),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 20,
                margin: const pw.EdgeInsets.only(right: 6),
                child: pw.Text(
                  '${numMatch.group(1)}.',
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                    color: const PdfColor.fromInt(0xFF6C63FF),
                  ),
                ),
              ),
              pw.Expanded(
                child: _buildRichText(numMatch.group(2)!),
              ),
            ],
          ),
        ));
        continue;
      }

      // Code block (```...```)
      if (trimmed.startsWith('```')) {
        final codeLines = <String>[];
        i++;
        while (i < lines.length && !lines[i].trim().startsWith('```')) {
          codeLines.add(lines[i]);
          i++;
        }
        if (codeLines.isNotEmpty) {
          widgets.add(pw.Container(
            width: double.infinity,
            margin: const pw.EdgeInsets.symmetric(vertical: 6),
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: const PdfColor.fromInt(0xFFF5F5F5),
              borderRadius: pw.BorderRadius.circular(6),
              border: pw.Border.all(
                color: const PdfColor.fromInt(0xFFDDDDDD),
              ),
            ),
            child: pw.Text(
              codeLines.join('\n'),
              style: pw.TextStyle(
                font: pw.Font.courier(),
                fontSize: 9,
                color: const PdfColor.fromInt(0xFF333333),
              ),
            ),
          ));
        }
        continue;
      }

      // Regular paragraph
      widgets.add(pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 4),
        child: _buildRichText(trimmed),
      ));
    }

    return widgets;
  }

  /// Build rich text with bold/italic support
  static pw.Widget _buildRichText(String text) {
    final spans = <pw.InlineSpan>[];
    final parts = text.split(RegExp(r'(\*\*.*?\*\*|\*.*?\*|`[^`]+`)'));

    for (final part in parts) {
      if (part.startsWith('**') && part.endsWith('**')) {
        spans.add(pw.TextSpan(
          text: part.substring(2, part.length - 2),
          style: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            fontSize: 11,
            color: const PdfColor.fromInt(0xFF222222),
          ),
        ));
      } else if (part.startsWith('*') && part.endsWith('*') && part.length > 2) {
        spans.add(pw.TextSpan(
          text: part.substring(1, part.length - 1),
          style: pw.TextStyle(
            fontStyle: pw.FontStyle.italic,
            fontSize: 11,
            color: const PdfColor.fromInt(0xFF555555),
          ),
        ));
      } else if (part.startsWith('`') && part.endsWith('`')) {
        spans.add(pw.TextSpan(
          text: part.substring(1, part.length - 1),
          style: pw.TextStyle(
            font: pw.Font.courier(),
            fontSize: 10,
            color: const PdfColor.fromInt(0xFF0099BB),
          ),
        ));
      } else if (part.isNotEmpty) {
        spans.add(pw.TextSpan(
          text: part,
          style: const pw.TextStyle(
            fontSize: 11,
            color: PdfColor.fromInt(0xFF333333),
          ),
        ));
      }
    }

    if (spans.isEmpty) {
      return pw.Text(
        text,
        style: const pw.TextStyle(
          fontSize: 11,
          color: PdfColor.fromInt(0xFF333333),
          lineSpacing: 4,
        ),
      );
    }

    return pw.RichText(
      text: pw.TextSpan(children: spans),
    );
  }

  /// Strip markdown formatting for plain text
  static String _stripInlineMarkdown(String text) {
    return text
        .replaceAll(RegExp(r'\*\*(.+?)\*\*'), r'$1')
        .replaceAll(RegExp(r'\*(.+?)\*'), r'$1')
        .replaceAll(RegExp(r'`([^`]+)`'), r'$1');
  }
}
